// import { Column } from "./type";

// export const COLUMNS: Column[] = [
//   {
//     id: "SiteID",
//     title: "SiteID",
//     width: 150,
//   },
//   { id: "ArrivalAirport", title: "ArrivalAirport", width: 150 },
//   { id: "WaybillOriginator", title: "WaybillOriginator", width: 150 },
//   { id: "AirlinePrefix", title: "AirlinePrefix", width: 150 },
//   { id: "AWBSerialNumber", title: "AWBSerialNumber", width: 150 },
//   { id: "HouseAWB", title: "HouseAWB", width: 150 },
//   { id: "MasterAWBIndicator", title: "MasterAWBIndicator", width: 150 },
//   { id: "OriginAirport", title: "OriginAirport", width: 150 },
//   { id: "Pieces", title: "Pieces", width: 150 },
//   { id: "WeightCode", title: "WeightCode", width: 150 },
//   { id: "Weight", title: "Weight", width: 150 },
//   { id: "Description", title: "Description", width: 150 },
//   { id: "FDAIndicator", title: "FDAIndicator", width: 150 },
//   { id: "ImportingCarrier", title: "ImportingCarrier", width: 150 },
//   { id: "FlightNumber", title: "FlightNumber", width: 150 },
//   { id: "ArrivalDay", title: "ArrivalDay", width: 150 },
//   { id: "ArrivalMonth", title: "ArrivalMonth", width: 150 },
//   { id: "ShipperName", title: "ShipperName", width: 150 },
//   { id: "ShipperStreetAddress", title: "ShipperStreetAddress", width: 150 },
//   { id: "ShipperCity", title: "ShipperCity", width: 150 },
//   {
//     id: "ShipperStateOrProvince",
//     title: "ShipperStateOrProvince",
//     width: 150,
//   },
//   { id: "ShipperPostalCode", title: "ShipperPostalCode", width: 150 },
//   { id: "ShipperCountry", title: "ShipperCountry", width: 150 },
//   { id: "ShipperTelephone", title: "ShipperTelephone", width: 150 },
//   { id: "ConsigneeName", title: "ConsigneeName", width: 150 },
//   {
//     id: "ConsigneeStreetAddress",
//     title: "ConsigneeStreetAddress",
//     width: 150,
//   },
//   { id: "ConsigneeCity", title: "ConsigneeCity", width: 150 },
//   {
//     id: "ConsigneeStateOrProvince",
//     title: "ConsigneeStateOrProvince",
//     width: 150,
//   },
//   { id: "ConsigneePostalCode", title: "ConsigneePostalCode", width: 150 },
//   { id: "ConsigneeCountry", title: "ConsigneeCountry", width: 150 },
//   { id: "ConsigneeTelephone", title: "ConsigneeTelephone", width: 150 },
//   { id: "CustomsValue", title: "CustomsValue", width: 150 },
//   { id: "CurrencyCode", title: "CurrencyCode", width: 150 },
//   { id: "HTSNumber", title: "HTSNumber", width: 150 },
//   { id: "ExpressRelease", title: "ExpressRelease", width: 150 },
//   { id: "TRACKING NUMBER", title: "TRACKING NUMBER", width: 150 },
// ];
